import { StyleSheet } from "react-native";

export const Styles=StyleSheet.create({
    contaier:{
        flex:1,
        margin:10,
    },
    pageWelcome:{
        fontSize:23,
        fontWeight:'bold',
    },
    signupContainer:{
        marginTop:5,
        backgroundColor:'#babab8',
        paddingLeft:5,
        paddingRight:5,
        paddingBottom:5,
        borderTopRightRadius:10,
        borderTopLeftRadius:10,
    },
    innerContainer:{
        backgroundColor:'white',
        paddingTop:5,
        paddingLeft:5,
        paddingRight:5,
        paddingBottom:15,
        borderBottomLeftRadius:10,
        borderBottomRightRadius:10,
    },
    inputContainer:{
        borderWidth:2,
        borderColor:'#8a8703',
        paddingLeft:5,
        paddingRight:5,
        borderBottomWidth:2,
        borderRadius:8,
    },
    input:{
        paddingLeft:10,
        paddingRight:3
    },
    inputIcons:{
        
    },
    lableStyle:{
        color:'#585959',
        textAlign:'right',
    },
    button:{
        margin:8,
        backgroundColor:'#a8a605',
        borderRadius:8,
        padding:12,
    },
    buttonIcon:{
        color:'white',
        marginLeft:6,
    },
    buttonTitleStyle:{
        fontSize:19,
    },
    errorMsg:{
        color:'#d10f25',
        marginBottom:5,
        marginLeft:10,
        marginRight:10,
        fontSize:17,
        fontStyle:'italic',
        fontFamily:'Roboto',
        textShadowColor: '#bf3444',
        textShadowOffset: { width: 0.5, height: 0.5 },
        textShadowRadius: 1, 
    },
    privacyPolicy:{
        marginLeft:8,
        marginRight:8,
    },
    overlayStyle:{
        width: '80%',
        padding:20,
        borderRadius:10,
    },
    overlayPleaseWait:{
        fontSize:18,
    },
    overlayVerifingCredentials:{
        marginTop:5,
        fontSize:16,
    },
    overlayActivityIndicator:{
        marginTop:10,
    },
    overlayViewLoginSuccess:{
        width:'100%',
        alignItems:'center'
    },
    overlaySignInSuccess:{
        fontSize:17,
    },
    overlaySuccessIcon:{
        width:50, 
        height:50, 
        alignContent:'center',
        marginTop:10,
        marginBottom:10,
    },
    overlaySuccessButtonIcon:{
        marginRight:10
    }
})