import { StyleSheet } from "react-native";

export const Styles=StyleSheet.create({
    contaier:{
        flex:1,
        margin:10,

    },
    inputContainer:{
        borderWidth:2,
        borderColor:'#abb0b8',
        borderBottomWidth:2,
        borderRadius:8,
        paddingLeft:7,
        paddingRight:7,
    },
    input:{
        paddingLeft:10,
        paddingRight:3
    },
    lableStyle:{
        color:'#585959',
        textAlign:'right',
    },
    buttonGroupContainer:{
        borderWidth:2,
        borderColor:'#abb0b8',
        height:50,
        borderRadius:8,
        marginBottom:25,
    },
    selectedButtonStyle:{
        backgroundColor:'#34558a'
    },
    textStyle:{
        fontSize:18
    },
    passwordHintText:{
        marginLeft:10,
        marginRight:10,
        marginBottom:10,
        textAlign:'justify',
    },
    button:{
        margin:8,
        backgroundColor:'#274575',
        borderRadius:8,
        padding:12
    },
    textComponetStyle:{
        fontWeight:'bold',
        color:'#5d5e5e',
        textAlign:'right',
        marginRight:10,
        fontSize:16,
    },
    buttonIcon:{
        color:'white',
        marginLeft:6,
    },
    bottomSheetTextTitleContainer:{
        marginLeft:10,
        marginRight:10,
        borderTopRightRadius:10,
        borderTopLeftRadius:10,
    },
    bottomSheetTextTitle:{
        fontSize:17,
    },
    bottomSheetTextContentContainer:{
        marginLeft:10,
        marginRight:10,
        backgroundColor:'#f7f7f7',
        borderBottomRightRadius:10,
        borderBottomLeftRadius:10,
    },
    bottomSheetTextContent:{
        fontSize:17,
    },
    bottomSheetProceedButtonContainer:{
        marginLeft:10,
        marginRight:10,
        backgroundColor:'#0f9799',
        textAlign:'right',
        borderRadius:10,

    },
    bottomSheetProceedButtonTitle:{
        fontSize:20,
        textAlign:'right',
        color:'white'
    },
    bottomSheetCancelButtonContainer:{
        marginLeft:10,
        marginRight:10,
        marginBottom:10,
        backgroundColor:'#732039',
        alignItems:'center',
        justifyContent:'center',
        borderRadius:10,
        textAlign:'center'
    },
    bottomSheetCancelButtonTitle:{
        fontSize:20,
        textAlign:'right',
        color:'white',
        textAlign:'center'
    },
    overlayStyle:{
        width: '80%',
        padding:20,
        borderRadius:10,
    },
    overlayPleaseWait:{
        fontSize:18,
    },
    overlayVerifingCredentials:{
        fontSize:16,
    },
    overlayActivityIndicator:{
        marginTop:10,
    },
    overlayViewLoginSuccess:{
        width:'100%',
        alignItems:'center'
    },
    overlaySignInSuccess:{
        fontSize:17,
    },
    overlaySuccessIcon:{
        width:50, 
        height:50, 
        alignContent:'center',
        marginTop:10,
        marginBottom:10,
    },
    overlaySuccessButtonIcon:{
        marginRight:10
    }
})