import { StyleSheet } from "react-native";
import appColors from '../../Others/appColors.json'
export const Styles=StyleSheet.create({
    contaier:{
        flex:1,
        margin:10,
    },
    pageWelcome:{
        fontSize:23,
        fontWeight:'bold',
    },
    signupContainer:{
        marginTop:5,
        backgroundColor:'#e8e7e6',
        paddingLeft:5,
        paddingRight:5,
        paddingBottom:5,
        borderTopRightRadius:10,
        borderTopLeftRadius:10,
    },
    signinContainer:{
        backgroundColor:'white',
        paddingTop:5,
        paddingLeft:5,
        paddingRight:5,
        paddingBottom:15,
    },
    inputContainer:{
        borderWidth:2,
        borderColor:appColors.basicRed,
        paddingLeft:5,
        paddingRight:5,
        borderBottomWidth:2,
        borderRadius:8,
    },
    input:{
        paddingLeft:10,
        paddingRight:3
    },
    inputIcons:{
        
    },
    lableStyle:{
        color:'#585959',
        textAlign:'right',
    },
    button:{
        margin:8,
        backgroundColor:'#9D1D27',
        borderRadius:8,
        padding:12,
    },
    buttonIcon:{
        color:'white',
        marginLeft:6,
    },
    buttonTitleStyle:{
        fontSize:19,
    },
    errorMsg:{
        color:'#d10f25',
        marginBottom:5,
        marginLeft:10,
        marginRight:10,
        fontSize:17,
        fontStyle:'italic',
        fontFamily:'Roboto',
        textShadowColor: '#bf3444',
        textShadowOffset: { width: 0.5, height: 0.5 },
        textShadowRadius: 1, 
    },
    privacyPolicy:{
        marginLeft:8,
        marginRight:8,
    },
    forgotPasswordContainer:{
        backgroundColor:'#e8e7e6',
        paddingLeft:5,
        paddingRight:5,
        paddingBottom:5,
        borderBottomRightRadius:10,
        borderBottomLeftRadius:10,
    },
})